# Generated by Django 5.1.7 on 2025-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("total_orders", models.IntegerField(default=0)),
                ("revenue", models.IntegerField(default=0)),
                ("water_delivered", models.IntegerField(default=0)),
                ("avg_order_value", models.IntegerField(default=0)),
                ("monthly_growth", models.TextField(default="{}")),
                ("top_clients", models.TextField(default="[]")),
                ("top_drivers", models.TextField(default="[]")),
                ("monthly_data", models.TextField(default="{}")),
                ("water_by_package", models.TextField(default="{}")),
                ("order_status", models.TextField(default="{}")),
                ("peak_delivery_times", models.TextField(default="{}")),
                ("client_growth", models.TextField(default="{}")),
            ],
        ),
    ]
