# Generated by Django 5.1.7 on 2025-03-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_analyticsdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard (500L)"),
                            ("Premium", "Premium (1000L)"),
                            ("Enterprise", "Enterprise (1500L)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("liters", models.IntegerField()),
                ("quantity", models.IntegerField(default=1)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("delivery_address", models.TextField()),
                ("delivery_date", models.DateField()),
                (
                    "delivery_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (9AM - 12PM)"),
                            ("afternoon", "Afternoon (12PM - 3PM)"),
                            ("evening", "Evening (3PM - 6PM)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
